---
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
spring:
  profiles: dev
  application:
    name: microservice-api-gateway
  aop:
    proxy-target-class: true
server:
  port: 8000
  session:
    timeout: 30
eureka:
  instance:
    preferIpAddress: false
    hostname: www.genesis.com
    instance-id: ${spring.application.name}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery1:8861/eureka/,http://discovery2:8862/eureka/
    region: chengdu #所属地区
    availabilityZones: #配置所有地区的有效zone
      chengdu: sichuan-zone
# ribbon启用okhttp客户端连接支持
ribbon.okhttp.enabled: true
# ribbon配置请求超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# 给每个服务单独配置连接属性
microservice-business:
  ribbon:
#    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0
microservice-webpay:
  ribbon:
#    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0

#zuul:
#  ignored-services:           # 需要忽视的服务(配置后将不会被路由)
#  routes:
#    movie:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = security-id时，security-id可以不写。
#      path: /movie/**                                   # 想要映射到的路径
#      security-id: microservice-consumer-movie-ribbon-with-hystrix    # Eureka中的serviceId
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization         #请求头黑名单

#auth2配置
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: ui2
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS
---
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
spring:
  profiles: prod
  application:
    name: microservice-api-gateway
  aop:
    proxy-target-class: true
server:
  port: 8000
  session:
    timeout: 30
eureka:
  instance:
    preferIpAddress: false
    hostname: 192.168.249.199
    instance-id: ${spring.application.name}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery1:8861/eureka/,http://discovery2:8862/eureka/
    region: chengdu #所属地区
    availabilityZones: #配置所有地区的有效zone
      chengdu: sichuan-zone
# ribbon启用okhttp客户端连接支持
ribbon.okhttp.enabled: true
# ribbon配置请求超时时间
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
# 给每个服务单独配置连接属性
microservice-business:
  ribbon:
#    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0
microservice-webpay:
  ribbon:
#    NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0

#zuul:
#  ignored-services:           # 需要忽视的服务(配置后将不会被路由)
#  routes:
#    movie:                                              # 可以随便写，在zuul上面唯一即可；当这里的值 = security-id时，security-id可以不写。
#      path: /movie/**                                   # 想要映射到的路径
#      security-id: microservice-consumer-movie-ribbon-with-hystrix    # Eureka中的serviceId
#      sensitiveHeaders: Cookie,Set-Cookie,Authorization         #请求头黑名单

#引入microservice-integration-authui.jar包后对auth2配置
security:
  oauth2:
    client:
      accessTokenUri: http://192.168.249.199:9999/uaa/oauth/token
      userAuthorizationUri: http://192.168.249.199:9999/uaa/oauth/authorize
      clientId: ui2
      clientSecret: secret
    resource:
      userInfoUri: http://192.168.249.199:9999/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS

