---
logging.level.root: debug
server:
  port: 8091
  session:
    timeout: 30
  workerId: 0
  datacenterId: 0
spring:
  profiles: chengdu-1
  application:
    name: microservice-business
  # DATA REDIS
  data:
    redis:
      repositories:
        enabled: true # Enable Redis repositories.
  redis:
    cluster:
      max-redirects: 4
      nodes:
        - 10.10.10.1:7000
        - 10.10.10.1:7001
        - 10.10.10.1:7002
#        - 192.168.248.143:7003
#        - 192.168.248.143:7004
#        - 192.168.248.143:7005
#        - 192.168.248.143:7006
#        - 192.168.248.143:7007
#        - 192.168.248.143:7008
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-Class-Name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.249.199:3306/microservice?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false&amp;useSSL=false
    username: truck
    password: jjb910123
    testWhileIdle: true
    validationQuery: SELECT 1
    maxIdle: 192
    minIdle: 64
    maxActive: 256
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    numTestsPerEvictionRun: 20
    minEvictableIdleTimeMillis: 300000
  mybatis:
    mapperLocations: classpath*:mapping/*.xml
    typeAliasesPackage: com.genesis.microservice.business.pojo
    mapperBasePackages: com.genesis.microservice.business.mapper
eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://discovery1:8861/eureka/,http://discovery2:8862/eureka/    # 指定注册中心的地址
    region: chengdu #所属地区
    availabilityZones: #配置所有地区的有效zone
      chengdu: sichuan-zone
  instance:
    preferIpAddress: false
    hostname: www.genesis.com
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  httpclient:
    enabled: true # ribbon启用okhttp客户端连接支持
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
#ribbon服务链接超时配置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
microservice-webpay:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0
#feign 进行请求压缩配置
feign:
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
wechat:
  ribbon:
    listOfServers: https://api.weixin.qq.com
  appid: wxbfcadef6ec2458f7
  secret: 58843d5cd8612e5ebef7240cbe324008
  token: testToken
  authorizeBackUrl: http://819e40a9.ngrok.io/wechat/login
---
logging.level.root: debug
server:
  port: 8091
  session:
    timeout: 30
  workerId: 0
  datacenterId: 0
spring:
  profiles: dev
  application:
    name: microservice-business
  # DATA REDIS
  data:
    redis:
      repositories:
        enabled: true # Enable Redis repositories.
  redis:
    cluster:
      max-redirects: 4
      nodes:
        - 10.10.10.1:7000
        - 10.10.10.1:7001
        - 10.10.10.1:7002
        - 10.10.10.1:7003
#        - 192.168.248.143:7003
#        - 192.168.248.143:7004
#        - 192.168.248.143:7005
#        - 192.168.248.143:7006
#        - 192.168.248.143:7007
#        - 192.168.248.143:7008
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-Class-Name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.248.143:3306/genesis01?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false&amp;useSSL=false
    username: root
    password: 123456
    testWhileIdle: true
    validationQuery: SELECT 1
    maxIdle: 192
    minIdle: 64
    maxActive: 256
    maxWait: 30000
    timeBetweenEvictionRunsMillis: 60000
    numTestsPerEvictionRun: 20
    minEvictableIdleTimeMillis: 300000
  mybatis:
    mapperLocations: classpath*:mapping/*.xml
    typeAliasesPackage: com.genesis.microservice.business.pojo
    mapperBasePackages: com.genesis.microservice.business.mapper
eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://discovery1:8861/eureka/,http://discovery2:8862/eureka/    # 指定注册中心的地址
    region: chengdu #所属地区
    availabilityZones: #配置所有地区的有效zone
      chengdu: sichuan-zone
  instance:
    preferIpAddress: false
    hostname: www.genesis.com
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  okhttp:
    enabled: true # ribbon启用okhttp客户端连接支持
  eureka:
    enabled: true         # 默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。参考：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#spring-cloud-ribbon-without-eureka
#ribbon服务链接超时配置
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
microservice-webpay:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
    # Connect timeout used by Apache HttpClient
    ConnectTimeout: 3000
    # Read timeout used by Apache HttpClient
    ReadTimeout: 60000
    # Max number of retries on the same server (excluding the first try)
    MaxAutoRetries: 0
    # Max number of next servers to retry (excluding the first server)
    MaxAutoRetriesNextServer: 0
#feign 进行请求压缩配置
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

